//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cinema_management.Models.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genre
    {
        public int GenreID { get; set; }
        public string GenreDisplayName { get; set; }
    
        public virtual Movie Movie { get; set; }
    }
}
