//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cinema_management.Models.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trouble
    {
        public string TroubleId { get; set; }
        public string TroubleTitle { get; set; }
        public string TroubleDescription { get; set; }
        public string TroubleStatus { get; set; }
        public System.DateTime TroubleSubmittedAt { get; set; }
        public decimal TroubleRepairCost { get; set; }
        public Nullable<System.DateTime> TroubleStartDate { get; set; }
        public Nullable<System.DateTime> TroubleFinishDate { get; set; }
        public string StaffId { get; set; }
        public string TroubleLevel { get; set; }
        public string Image { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
