//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cinema_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductReceipt
    {
        public string ProductReciptID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<decimal> ImportPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public byte[] TimeOfReceipt { get; set; }
        public string StaffID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
